version: '3.1'

services:
  postgres:
    image: postgres
    container_name: store_postgres
    ports:
      - ${DB_PORT}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fullstack
    volumes:
      - ./schema:/schema
    command: ["-path", "/schema", "-database", "postgres://postgres:${DB_PASSWORD}@postgres:${DB_PORT}/postgres?sslmode=disable", "up"]
  store_api:
    container_name: store_api
    build: .
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - api_volume:/usr/src/app
    depends_on:
      - migrate
    networks:
      - fullstack
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"


volumes:
  postgres_data:
  api_volume:
networks:
  fullstack:
    driver: bridge